const cpx = require('cpx')
cpx.copy('node_modules/animate.css/*.css', 'public/vendor/animate.css')
cpx.copy('node_modules/bootstrap/dist/**/*.*', 'public/vendor/bootstrap')
cpx.copy('node_modules/jquery/dist/*.*', 'public/vendor/jquery')
cpx.copy('node_modules/@fortawesome/fontawesome-free/css/*.*', 'public/vendor/fontawesome-free/css')
cpx.copy('node_modules/@fortawesome/fontawesome-free/js/*.*', 'public/vendor/fontawesome-free/js')
cpx.copy('node_modules/@fortawesome/fontawesome-free/sprites/*.*', 'public/vendor/fontawesome-free/sprites')
cpx.copy('node_modules/@fortawesome/fontawesome-free/svgs/**/*.*', 'public/vendor/fontawesome-free/svgs')
cpx.copy('node_modules/@fortawesome/fontawesome-free/webfonts/*.*', 'public/vendor/fontawesome-free/webfonts')
